## pokud upravíme je potřeba restart server
collections:
  kalistenika:
    output: true
    permalink: /:name

  hry:
    output: true
    permalink: /:name


instagram: https://www.instagram.com/suche.cz
facebook: https://facebook.com/suche.cz
messanger: https://m.me/suche.cz

plugins:
  - jekyll-sitemap


defaults:
  - scope:
      path: "assets/img/cviky/1"
    values:
      cviky1: true

  - scope:
      path: "assets/img/cviky/2"
    values:
      cviky2: true

  - scope:
      path: "assets/img/cviky/3"
    values:
      cviky3: true

  - scope:
      path: "assets/img/cviky/4"
    values:
      cviky4: true

  - scope:
      path: "assets/img/galerie/ranni-trenink"
    values:
      galerie_ranni_trenink: true

  - scope:
      path: "assets/img/galerie/nedelni-trenink"
    values:
      galerie_nedelni_trenink: true


## pokud upravíme je potřeba restart server